### ISSUE TITLE
Improve benefit heuristic around `[@inline]` annotated functions

### ISSUE THREAD

**Issue by chambart** [OCamlPro/flambda-task-force#103]
Inlining an higher order function can uncover a new opportunity for inlining an `[@inline]` function. In those cases. The first function risk to be prevented from inlining. For instance with `Array.fold_left`

```ocaml
let f x y = x +. y +. x +. y +. x +. y
  [@@inline] (* annotated since there is potentially a huge benefit from unboxing *)
let g a = Array.fold_left f 0. a
```
The size of `f` will count in the cost of unboxing `g` and will potentially prevent something that was annotated by the programmer as a good inline decision.

Since the annotation `[@inline]` morally mean: consider that the benefit of inlining this function is exactly its size, we could really give it that exact meaning for the parent functions: add to the benefit the size of the inlined expression.

Does anyone see a flaw that may trigger some unreasonable behavior ?

**Comment by mshinwell** [comment]
Slightly related: I'm working on a change that I hope will speed up inlining significantly.  The idea is to accumulate the code size during Inline_and_simplify (basically by changing "ret" to look at the toplevel constructor and keeping the code size in "r").  This should save the traversal in [lambda_smaller].  Also, if "ret" finds out that the code size has become too large, it's going to throw an exception to abort that simplification (which can then be caught in Inlining_decision).  This should prevent us simplifying parts of terms that will immediately be discarded.  I haven't quite worked out how to tie this into [Whether_sufficient_benefit] yet, but I'm looking at that now.

**Comment by mshinwell** [comment]
Hmm, but there may be a problem with trying to escape early, because the benefit could potentially be very large in the part after that.

**Comment by chambart** [comment]
I just pushed the change to take into account the inlined function for its parents.

**Comment by lpw25** [comment]
> Since the annotation [@inline] morally mean: consider that the benefit of inlining this function is exactly its size

Doesn't [@inline] morally mean: always inline this regardless of whether the compiler thinks it's a good idea?

**Comment by chambart** [comment]
Normally the inlining threshold is meant to prevent arbritrary high cost of traversal.
It is not fixed: it starts at toplevel at a given size (-inline) and decrease each time
we made a decision to try inlining.
```ocaml
let f g x = g x
let v = f g 3
```
When inlining f, its size will be compared with the initial threshold (t), and when
exploring its body, the threshold against which the size of g is evaluated
is (t - size(f)). That way, when evaluating something for inlining we cannot try
arbitrary deeply because the depth is bound by the remaining size. And we also
cannot try inlining a sub-function that would completely prevent an ancessor.

**Comment by chambart** [comment]
@lpw25 Yes, but only for the call site. For the parent call site we cannot consider it that way. So considering that the benefit is exactly the size, implies "do it even if it does not look like a good idea" with a meaning that we can propagate.

**Comment by lpw25** [comment]
Ok, I think I understand. Out of interest would:

```ocaml
let f x y = x +. y +. x +. y +. x +. y  [@@inline]

let g a = (Array.fold_left [@inlined]) f 0. a
```

behave as I would hope with your new criteria?

**Comment by lpw25** [comment]
> let f x y = x +. y +. x +. y +. x +. y  [@@inline]
>
> let g a = (Array.fold_left [@inlined]) f 0. a

Actually, I meant:

```ocaml
let f x y = x +. y +. x +. y +. x +. y  [@@inline]

let g a = (Array.fold_left [@specialised]) f 0. a
```

**Comment by chambart** [comment]
In fact `Array.fold_left` is not recursive. But considereing it is:
With both annotations it is guaranteed to be inlined. But that was also the case before. Without the specialised annotation it is guaranteed to be inlined if `Array.fold_left` is sufficiently beneficial by itself. But if inlining `Array.fold_left` is a really bad choice, it will not.

By the way I gave the function only its size as benefit, but it may be reasonnable to give to the caller a benefit for 'finding' that opportunity.

**Comment by mshinwell** [comment]
So I have a better idea for making things faster which might actually work.  More on this tomorrow...

**Comment by mshinwell** [comment]
This is the idea
https://github.com/chambart/ocaml-1/pull/8/files

**Comment by mshinwell** [comment]
@lpw25 Has the original problem here been fixed?

**Comment by lpw25** [comment]
I think this has been addressed. @chambart can you confirm that you have implemented this idea?

**Comment by chambart** [comment]
@lpw25 effectively.
