### ISSUE TITLE
Propagate the `[@inlined]` attribute inside inlined stubs

### ISSUE THREAD

**Issue by chambart** [OCamlPro/flambda-task-force#104]
In the following example:
```ocaml
let f (x,y) = ...
let g x = (f [@inlined]) (x,x)
```
The `f` function will be split in a stub and a the curried function:

```ocaml
let f' x y = ...
let f (x,y) = f' x y [@@stub]
```

For the inlining decision at the call site inside  `g` both the stub and inlined annotation will appear, and the stub will be inlined. But in that case the programmer really meant for the `f'` function to be inlined (the stub is not visible in the sources).

The right way to propagate that is probably when this case is encountered (`inline_requested` is `true` and `function_decl.stub` is not `Default_inline`) to rewrite the stub body to annotate the calls with the same inilne annotation.

**Comment by lpw25** [comment]
I think this is essentially a duplicate of #86

**Comment by chambart** [comment]
Oups, exactly.
