### ISSUE TITLE
Disappointing result with functor

### ISSUE THREAD

**Issue by alainfrisch** [OCamlPro/flambda-task-force#115]
I tried the following micro benchmark:

````ocaml
module X = Set.Make(struct
    type t = int
    let compare (x : int) y = compare x y
end)

let () =
  let n = ref 0 in
  let s = X.singleton 10 in
  for i = 1 to 100000000 do
    if X.mem i s then incr n
  done
````

My hope was that the functor would be inlined, and then `compare`, thus avoiding some (indirect) function calls.  This is not the case with default parameters, and I did not manage to achieve it by tweaking command-line arguments.  Is that possible?

Anyway, with default parameters,  the code above is about 20% slower than with trunk.  I did not investigate in details where it comes from, but I noticed that calls to X.mem go through caml_apply2:

````
        (let
           (apply_funct_29/1406
              (load val (+a (load val "camlTest_inline__X_49") 8))
            cond_30/1407
              (app{../test_inline.ml:10,7-16} "caml_apply2" i_25/1404
                s_20/1401 apply_funct_29/1406 val))
````

to be compared to:

````
                    (app "camlSet__mem_3345" i/1265 s/1264
                       (load val (+a (load val "camlTest_inline") 8)) val)
                     1)
````

(I'm also a tiny bit concerned by the extra verbosity of the various intermediate languages outputs such as extra bindings anddouble "unique ids" appended to identifiers.)

**Comment by mshinwell** [comment]
This is probably related to the new code for inlining functors.  Pierre, can you please investigate?

**Comment by chambart** [comment]
The current default lifting benefit is 100. In that example the inlined version of Set.Make is ~650.

So it is apparently really too small. The question is how to choose it correctly. The previous version was to always inline it. I will augment seriously the default.

As for the indirect call to X.mem, is is due to the lack of return approximation for functions. This is a current limitation that should be lifted at some point. I did not bother too much to fix that since the only case where this was useful were functor application (or equivalent variants with records) and this was almost always handled by the functor inlining.

**Comment by chambart** [comment]
The not so unreasonable arguments to try for that example is:
```
-inline-toplevel 100 -inline-lifting-benefit 1000 -inline-call-cost 20 -unroll 2
```

**Comment by alainfrisch** [comment]
> -inline-toplevel 100 -inline-lifting-benefit 1000 -inline-call-cost 20 -unroll 2

This is indeed enough to completely inline the functor in that case.  There remains a missing trivial optimization of the equality:
````
 (let c_2545/1676 (extcall "caml_int_compare" i_25/1674 21 val)
           (catch (if (== c_2545/1676 1) (if (!= 3 1) (exit 8) []) [])
           with(8)
````

It's perhaps dangerous to rely on a threshold to decide whether to inline or not.  This can drastically impact the performance of the code using the functor, and you don't want to get very degraded performance simply because the functor's body got a little bit bigger.  Moreover, a default threshold that would be enough to force inlining of "useful cases" (such as data structures used in tight code) could very well trigger way too many inlining, resulting in code size explosion, which can have bad effects on performances (load time, cache misses).

Is there a way to force inlining of a specific functor application?

**Comment by mshinwell** [comment]
I think we're planning to let people annotate the functor declaration and/or application point (the same as for functions) with an inlining attribute, yes.

**Comment by mshinwell** [comment]
I will have a look at why that equality wasn't optimised.

**Comment by chambart** [comment]
The previous versions of the 'functor-heuristic' didn't rely on a threshold, and did inline systematically when a functor was applied at toplevel.
Now this one prevent it if the functor is really too big. This prevent arbitrarilly unbounded augmentation in compile time (That can still be quite big. This example is like compiling the whole set module).

**Comment by chambart** [comment]
The `if (!= 3 1)` is introduced by cmmgen.

**Comment by alainfrisch** [comment]
> As for the indirect call to X.mem, is is due to the lack of return approximation for functions. This is a current limitation that should be lifted at some point.

Since not all functors will be inlined, it would indeed be rather good not to loose too much when calling a known function in a functor's body.

**Comment by mshinwell** [comment]
@chambart Did you look at the cmmgen thing?

**Comment by mshinwell** [comment]
We think this was fixed.
