### ISSUE TITLE
Collect packages building with trunk

### ISSUE THREAD

**Issue by chambart** [OCamlPro/flambda-task-force#12]

**Comment by lefessan** [comment]
Use `opam-depext -l PACKAGE.VERSION` to prepare the environment

**Comment by AltGr** [comment]
I set opam up for performing coverage of all packages; gathering data from early batch-run results gives 483 packages compiling on trunk, 64 packages broken and 305 packages depending on the broken packages.

Note that the coverage is not optimal, as it's not adapted to the actual installation results (e.g. if you have an optional dependency on A and were planned in the same batch run, you'll be skipped if A fails to install).

Current list of packages here: https://gist.github.com/AltGr/6dd51a4457d909997be2
