### ISSUE TITLE
Sharing partial applications

### ISSUE THREAD

**Issue by lpw25** [OCamlPro/flambda-task-force#127]
I notice a lot of identical functions in the output of -dcmm which are the results of partially applying the same function. We should probably make some attempt to share these.

**Comment by lpw25** [comment]
Actually looking again. It seems that my examples all come from the *same* partial application, with the definition of the partial application function having been copied each time the surrounding function was inlined or specialised.

**Comment by mshinwell** [comment]
Superceded by #128
