### ISSUE TITLE
Wrong sharing of float array literals

### ISSUE THREAD

**Issue by alainfrisch** [OCamlPro/flambda-task-force#134]
````ocaml
let a =
  [|
    [| 0.; 2.; 3.; 0.; 9.;  0.; 2.; 3.; 0.;|];
    [| 0.; 2.; 3.; 0.; 9.;  0.; 2.; 3.; 0.;|];
  |]


let () =
  a.(0).(0) <- 10.;
  Printf.printf "%f\n%!" a.(1).(0)
````

This prints 0. with ocaml trunk, but 10. with flambda_trunk (configured with -flambda). (Wrong) sharing of float array literals does not seem to happen with smaller array sizes.

**Comment by mshinwell** [comment]
We are looking at this in London

**Comment by mshinwell** [comment]
It looks like lift_constants.ml:389 is probably wrong.  I'll try to fix this, might be tomorrow.

**Comment by mshinwell** [comment]
Fixed in flambda_trunk.  Thanks for the report.
