### ISSUE TITLE
Fix order of functions

### ISSUE THREAD

**Issue by mshinwell** [OCamlPro/flambda-task-force#142]
The ordering of toplevel functions in the source file should be the ordering in which the functions are emitted in the object file, so people can re-order functions as they wish to help cache locality.  At present, anonymous functions (whose symbol names include locations generated by Flambda) break this, and even changes such as removing a comment can lead to highly unexpected effects.

**Comment by chambart** [comment]
merged: https://github.com/ocaml/ocaml/commit/d74d636a529b50f99fc8818f405d964445fb0fe0
