### ISSUE TITLE
Prepare code coverage infrastructure for the compiler

### ISSUE THREAD

**Issue by chambart** [OCamlPro/flambda-task-force#2]

**Comment by hnrgrgr** [comment]
See the package ```ocaml-bisect``` in [opam-flambda-repository-overlay](https://github.com/OCamlPro/opam-flambda-repository-overlay).

It intruments the Flambda compiler with [ppx_bisect](https://github.com/rleonid/bisect_ppx), then run the OCaml testsuite, and eventually generate a coverage report.

```
OPAMROOT_ALT=${HOME}/.opam-flambda
opam init --root ${OPAMROOT_ALT} --compiler 4.03.0+flambda flambda-overlay https://github.com/OCamlPro/opam-flambda-repository-overlay.git
eval $(opam config --root ${OPAMROOT_ALT} env)
opam install --build-test ocaml-bisect
xdg-open $(ocamlfind query ocaml-bisect)/coverage/
```

The instrumented compiler is also installed as ```ocamlc-bisect.opt``` and ```ocamlopt-bisect.opt```.

**Comment by lefessan** [comment]
Would it be possible to include the  opam-flambda-repository-overlay GIT repo into this repo as a sub-directory, and still use it from OPAM ?
I am not fond of the multiplication of repositories, I prefer when everything related to the task force is included in the same repo..
Your opinion ?

**Comment by AltGr** [comment]
git doesn't allow cloning subdirs, and opam doesn't in general allow using a subdir of what was fetched. But we could have subdirs and advise to first `git clone` / `git update` and then use local repositories.
