### ISSUE TITLE
Import numerical benchmarks to operf-micro

### ISSUE THREAD

**Issue by chambart** [OCamlPro/flambda-task-force#21]
The libraries provided in https://github.com/nomaddo/ocaml-numerical-analysis seems to be good numerical benchmarks written in a non-contrived hand optimized style.

**Comment by mshinwell** [comment]
Michael, please have a look at this

**Comment by mshinwell** [comment]
@Michaaell Ping.

**Comment by Michaaell** [comment]
This is done
