### ISSUE TITLE
Permit use of old closure.ml

### ISSUE THREAD

**Issue by mshinwell** [OCamlPro/flambda-task-force#46]
It seems that people would like an option to disable the Flambda passes entirely, and use the legacy closure.ml code, until it has more of a proven track record.

**Comment by lefessan** [comment]
This sounds difficult to do (the cmx files now contain flambda code, which does not make sense for non-flambda passes), and also counter-productive (it might give the impression that flambda does not work and that people should keep the former way). For me, the goal of this work now is to prove that flambda (with the good parameters) is a better choice than the old versions.

For these people, I would actually propose to have a ./configure --disable-inlining that just turns most parameters to 0 and completely disable inlining.

**Comment by AltGr** [comment]
I would be tempted to answer that to stick with legacy implementations, they should simply stick to 4.02 until 4.03 has a proven track record -- which is the normal thing everybody does; any details on the reasons they would not be willing to do so ?

**Comment by mshinwell** [comment]
I think this is an essential feature.  People can't keep switching back and forwards between compiler versions since there are language changes (and some people may have to move forwards due to bug fixes).  It's not hard to do this, so we should do so.  It seems only sensible given the amount of new code we're introducing.

**Comment by mshinwell** [comment]
We decided not to do this
