### ISSUE TITLE
Execution time benchmarks

### ISSUE THREAD

**Issue by mshinwell** [OCamlPro/flambda-task-force#47]
We need a good, reproducible set of these.

**Comment by OCamlPro-Henry** [comment]
I think its a dup of #13.

**Comment by mshinwell** [comment]
I think this one's important enough to deserve it's own issue.

Benchmarks we need to add:
- CompCert
- Some code from Benoit
- Write some tests that use the newly-released Incremental library

**Comment by chambart** [comment]
* Facebook flow
