### ISSUE TITLE
Prepare a default setting for flambda without regressions

### ISSUE THREAD

**Issue by chambart** [OCamlPro/flambda-task-force#5]
The proposed default setting shouldn't:
* increase too much the binary size
* increase too much the compilation time
* be slower on any example

**Comment by lefessan** [comment]
Pierre : the arguments to control inlining are:
* `-inline N` : at a given function call, recursively inline only functions whose size is smaller than N x F (where F is some internal factor ~ 8)
   [we should search between 0 and 10, current default is 10, former compiler was ~1 ]
* `-rounds N` : number of iterations of the inliner (controls compilation time)
   [between 0 and 3, current default is 1, former compiler was ~1 ]
* `-unroll N` : max number of recursive inlining
   [between 0 and 2, current default is 0, former compiler was ~0]
* `-no-functor-heuristics` : disables functor inlining
   [current default is `false`, former compiler was `true`]
* `-inline-call-cost N`: max size of code when replacing a call
   [current default is 5, we should search between 1 and 5]
* `-inline-alloc-cost N`: estimated win when removing an allocation
  [current default is 10, we should search between 1 and 15]
* `-inline-prim-cost N` : estimated win when removing any other primitive
  [current default is 3, we should search between 1 and 5]
* `-inline-branch-cost N` : estimated win when removing an `if`
  [current default is 10, we should search between 1 and 10]

**Comment by lefessan** [comment]
* installation size

Interesting to measure, in particular if we can decrease the size of cmxas, we should target that (all .cmx + .cmxa + all .o) do not increase too much (< 1.2.)

**Comment by lefessan** [comment]
Try to write a script to run it everyday...
