### ISSUE TITLE
tests/asmcomp/staticalloc.ml

### ISSUE THREAD

**Issue by mshinwell** [OCamlPro/flambda-task-force#53]
There is at least one Initialize_symbol in here that looks like it should be a Let_symbol.  This construction also contains unused let-bound variables "x" and "y" which should not be there.

**Comment by chambart** [comment]
There was something weird in the last flambda:

```
initialize_symbol
  (Staticalloc.camlStaticalloc__a_1441 0
     (let
       (y/1531 Const(2)
        x/1533 Const(1)
        Pmakeblock/1534 Staticalloc.camlStaticalloc__Pmakeblock_1585)
       Pmakeblock/1534))
```

**Comment by mshinwell** [comment]
I checked this with and without -O3 and the flambda now looks ok.
