### ISSUE TITLE
Backtraces for compiler debugging

### ISSUE THREAD

**Issue by mshinwell** [OCamlPro/flambda-task-force#58]
This needs an upstream PR as discussed at the dev meeting.

**Comment by trefis** [comment]
X-ref: https://github.com/ocaml/ocaml/pull/300

**Comment by mshinwell** [comment]
@trefis This isn't just about the -g option, though: Pierre's patch also makes the backtraces work properly so they don't all say "parsing/location.ml"...

**Comment by mshinwell** [comment]
Closing this, there is an upstream GPR
