### ISSUE TITLE
Write the descriptive document 

### ISSUE THREAD

**Issue by chambart** [OCamlPro/flambda-task-force#6]
Needs to:
* [ ] https://github.com/OCamlPro/flambda-task-force/issues/22 justify the representation
* [ ] https://github.com/OCamlPro/flambda-task-force/issues/23 justify the heuristics
* document every corner case with examples
* explained included pass, and why they where needed for a first version

**Comment by lefessan** [comment]
You should avoid tasks "too generic". When will this task be finished ? Instead, you should already split it in multiple simple items, that you can easily finish in one day or two.

**Comment by mshinwell** [comment]
mshinwell is going to incorporate the document into the comments in the .mli files and the manual.

**Comment by mshinwell** [comment]
The manual has been done now.
