### ISSUE TITLE
Functor heuristics change

### ISSUE THREAD

**Issue by mshinwell** [OCamlPro/flambda-task-force#64]
Mark functions that are actually functors, which should now be easy after the change to use a record type.
Then, functor heuristics don't need to be heuristics.
We might want another option that enables the existing heuristic to be used for things that are not functors.

**Comment by lpw25** [comment]
I don't think we should treat functors specially: I think the important split for heuristics is between top-level functions (including functors) and non-toplevel functions.

I can see the motivation for having the "-functor-heuristics" flag to improve the predictability of inlining, but I think it would be better to rename it to something like "-inline-all-toplevel" or similar, or to remove it and rely on using "[@inline]" to control such inlining.

**Comment by chambart** [comment]
I pushed the first patch to annotate functions in lambda with the fact that they are functors.

**Comment by chambart** [comment]
@lpw25 I think that usualy programmers have a different assumption on how functor and functions are specialized. I still think that the current "-functor-heuristics" should be kept as-is, and effectively the current name isn't good.

But there is still a place for being a bit more aggressive for functors. In particular, the current heuristics trigger only if the arguments of the function are known to be useful. But in the classical way to use functor at toplevel, it is often beneficial even when the code cannot really be specialised for the arguments. Genrating fresh functions often allows to assign them symbols and make direct accesses, allowing more functions to be closed. But maybe this could be decided using the approximation of the function return: if it is an immutable block containing functions, it could trigger an almost certain inlining at toplevel.

**Comment by lpw25** [comment]
> I think that usualy programmers have a different assumption on how functor and functions are specialized.

Sure, but I can't help but feel that treating functors differently to functions on records is too "syntactic" a way to decide optimisations.

>  But maybe this could be decided using the approximation of the function return: if it is an immutable block containing functions, it could trigger an almost certain inlining at toplevel.

That sounds like a great way to do it. It directly captures why you want to inline these things in the first place.

**Comment by lpw25** [comment]
I was just surprised by some inlining even when I set the threshold to "-100000000000000". The cause was that "functor heuristics" overrides the inline threshold.

I actually think it would be better if it was "functor multiplier" (except with a better word than functor) and took a number to multiply the threshold by when dealing with functor-like functions.

The default should obviously be very high, but I think saying that "for functors the threshold is infinity" is too aggressive: at some point it really would be better not to inline the functor.

**Comment by chambart** [comment]
Since we don't have the approximation of function return yet, I propagated the functor property to flambda. I made the heuristic trigger on application even if no useful information is known for the arguments if it is a functor. This may be too much, we will see with this night's build.

Also I'm not sure of how to choose a limit for functor inlining.

**Comment by mshinwell** [comment]
The functor heuristics thing seems to be causing various problems in real-world code (see other issues that were submitted last night).

Concrete proposal as discussed with lwhite:
1. Add some kind of benefit factor for "being toplevel"
2. Add some kind of benefit factor for "returning record of functions" (which would for the moment only be triggered if we know the thing is a functor, since our approximations aren't powerful enough for anything else)
3. Make anything that is either "toplevel" or "record of functions" have the normal inlining thresholds etc applied to it, rather than being inlined unconditionally.

**Comment by lpw25** [comment]
Ok, I'm going to work on this now. The basic idea is to replace `-functor-heuristics` by:

1. A separate toplevel inlining threshold used for call sites at the top-level (set by `-inline-toplevel`). The reasoning being that we don't care as much about the instruction cache for things at the toplevel, and they can open up more opportunities for lifting. It will default to the regular inline threshold multiplied by some value.

2. A compiler option `-inline-lifting-benefit` which is added to the benefit of functions that lift things when they are called at toplevel. For now we will define "functions that lift" things as functors for which all their parameters have useful approximations. In the future we will use improved approximation information to consider any function whose return value contains closures (or other things for which lifting is beneficial).

**Comment by lpw25** [comment]
I written a patch for this [here](https://github.com/lpw25/ocaml/commit/fcc166878b13ca758d100aaae5d92f4f2eea84f6). It compiles but I haven't had a chance to test it.

**Comment by mshinwell** [comment]
This has all been sorted out now, I think.
