### ISSUE TITLE
Bad complexity in Lift_let_to_initialize_symbol

### ISSUE THREAD

**Issue by mshinwell** [OCamlPro/flambda-task-force#69]
mshinwell will provide pchambart with a test case that takes 10 minutes on a fast machine.

**Comment by mshinwell** [comment]
I think the k_means benchmark (file dataset.ml) is probably an example of the same thing.  Pierre, please have a look at that first, and then I can retest on the JS example.

**Comment by chambart** [comment]
I reworked it, It may be a bit more expensive in general, but does not have the bad cases anymore.
