### ISSUE TITLE
Make an opam repository for build with trunk

### ISSUE THREAD

**Issue by chambart** [OCamlPro/flambda-task-force#8]
We will need to patch packages to build with trunk:
* Fork a base repository at a fixed time (not to be updated)
* Maintain patch to be upstreamed in an overlay
* Move patch to the fork when upstreamed

**Comment by hnrgrgr** [comment]
Introduced:
* https://github.com/OCamlPro/opam-flambda-repository
* https://github.com/OCamlPro/opam-flambda-repository-overlay

Synchronized (with full archives) : 

https://flambda.ocamlpro.com/
