### ISSUE TITLE
Investigate Cstruct build failure

### ISSUE THREAD

**Issue by chambart** [OCamlPro/flambda-task-force#81]
[Last build](http://ns3000900.ip-37-59-47.eu/operf/2015-11-24-0754-a1960b91-8275515e/build.html#log-flambda-opt+bench-cstruct-1.6.0) with opt options triggered an error.

**Comment by mshinwell** [comment]
I am investigating this

**Comment by mshinwell** [comment]
I built this with:

OCAMLPARAM="_,inline=50,rounds=3,unroll=1,inline-call-cost=20,inline-alloc-cost=3,inline-prim-cost=3,inline-branch-cost=3,functor-heuristics=1" opam install cstruct -v -v -v -v -v -v

(although the compiler itself was not built with these options) and I did not manage to reproduce the failure.

**Comment by mshinwell** [comment]
I am closing this, I think it has been fixed.
