### ISSUE TITLE
Inlined always attributes ignored on applications with tuplified stubs

### ISSUE THREAD

**Issue by lpw25** [OCamlPro/flambda-task-force#86]
A tuplifying stub replaces an application of the stub function with a fresh application whose inline attribute is `Default_inline`. This means any `Always_inline` attribute on the original application is ignored. For example:

```ocaml
let f x y z =
  x * y * z

let x = (f [@inlined always]) 2 3 4

let g (x, y, z) =
  x * y * z

let y = (g [@inlined always]) (2, 3, 4)
```

with `-inline -100000000000 -no-functor-heuristics` will inline the call to `f` but not the call to `g`.

I think that the application inside the stub should be marked in some way to indicate that it should inherit its attribute from the application of the stub. Possibly it should inherit the debug info as well.

**Comment by mshinwell** [comment]
Pierre, the proposal is that when we copy the body of a function for inlining, we do a toplevel traversal looking for Apply, and if such an Apply is specially marked then we set its inlining and debug info information to match what we see at the stub's call site.

I can implement this if you think it's ok.
