### ISSUE TITLE
Opaque does not prevent `-functor-heuristics` from firing

### ISSUE THREAD

**Issue by lpw25** [OCamlPro/flambda-task-force#88]
Since `-functor-heuristics` is only supposed to apply to known arguments, I would expect:

```ocaml
let f x y z =
  x * y * z

let x = f (opaque 2) 3 4
```

with `-inline -10000000` not to inline the call to `f`, but it does.

**Comment by lpw25** [comment]
In fact it inlines the whole thing down to `24` which means `opaque` really isn't working, since it should not be possible to see that the value is `2` which is necessary to get `24`.

**Comment by mshinwell** [comment]
I will investigate what is wrong with "opaque" tomorrow (2015-11-27).

**Comment by mshinwell** [comment]
@lpw25 This should be fixed now, please confirm, and then close this issue if so.

**Comment by lpw25** [comment]
Yes it is fixed now
