### ISSUE TITLE
No error on wrong attribute

### ISSUE THREAD

**Issue by lpw25** [OCamlPro/flambda-task-force#89]
It is quite easy to write `[@inline]` when you mean `[@inlined]`. Perhaps this should give a warning or error. Possibly this should be addressed separately alongside all other misuse of compiler supported attributes.

**Comment by mshinwell** [comment]
I'm hoping that Jeremie will be able to look at this.

**Comment by mshinwell** [comment]
Jeremie tested this, and it now appears to be fine.
