### ISSUE TITLE
slow compilation of tsdl in Mantis 7067 can be solved by flambda

### ISSUE THREAD

**Issue by marklrh** [OCamlPro/flambda-task-force#98]
A follow up from OCL compiler hacking session [issue](https://github.com/ocamllabs/compiler-hacking/wiki/Things-to-work-on#investigate-the-performance-of-flambda-on-the-tsdl-example)

The flambda branch can help eliminate the slowdown of [Mantis 7067](http://caml.inria.fr/mantis/view.php?id=7067)

real	0m0.217s
user	0m0.140s
sys	0m0.064s

In thread on Mantis,
[Alain replies Mark](http://caml.inria.fr/mantis/view.php?id=7067#c14916):
> Thanks. So indeed this might very well fix this problem

Yes, this is correct ...

**Comment by marklrh** [comment]
One problem is that [the operator ``{}``](https://github.com/dbuenzli/tsdl/blob/master/test/test.ml#L131) is not defined when compiling using latest trunk of flambda, so I removed them, which I don't think actually matters. 

The error is 
````
Error: Unbound value .{}
````

**Comment by mshinwell** [comment]
The error about the indexing operator will go away soon when the "Bigarray operators" patch is reverted upstream.
